id: I441399A3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T03:19:39+00:00'
last_modified: '2022-06-08T06:07:10.545917+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21664
  title: བོད་བརྒྱུད་ནང་བསྟན་ལྷ་རིས་ཀྱི་ཐིག་རྩ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '0473':
      image_group_id: I1PD36393
      title: ''
      total_pages: 304
      order: 1
      base_file: 0473.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
